// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type httpMonitorHttpEvent struct {
	Pid    uint32
	Comm   [16]int8
	Method [8]int8
	Path   [128]int8
}

// loadHttpMonitor returns the embedded CollectionSpec for httpMonitor.
func loadHttpMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load httpMonitor: %w", err)
	}

	return spec, err
}

// loadHttpMonitorObjects loads httpMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*httpMonitorObjects
//	*httpMonitorPrograms
//	*httpMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttpMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttpMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// httpMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpMonitorSpecs struct {
	httpMonitorProgramSpecs
	httpMonitorMapSpecs
}

// httpMonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpMonitorProgramSpecs struct {
	TraceTcpSendmsg *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg"`
}

// httpMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpMonitorMapSpecs struct {
	HttpEvents *ebpf.MapSpec `ebpf:"http_events"`
}

// httpMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpMonitorObjects struct {
	httpMonitorPrograms
	httpMonitorMaps
}

func (o *httpMonitorObjects) Close() error {
	return _HttpMonitorClose(
		&o.httpMonitorPrograms,
		&o.httpMonitorMaps,
	)
}

// httpMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpMonitorMaps struct {
	HttpEvents *ebpf.Map `ebpf:"http_events"`
}

func (m *httpMonitorMaps) Close() error {
	return _HttpMonitorClose(
		m.HttpEvents,
	)
}

// httpMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttpMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpMonitorPrograms struct {
	TraceTcpSendmsg *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
}

func (p *httpMonitorPrograms) Close() error {
	return _HttpMonitorClose(
		p.TraceTcpSendmsg,
	)
}

func _HttpMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed httpmonitor_x86_bpfel.o
var _HttpMonitorBytes []byte
