package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -type http_event httpMonitor ./bpf/http_monitor.c -- -I./bpf

// TODO 1: Define Prometheus metric
// Hint: Use prometheus.NewCounterVec with labels: method, path, comm
// This metric will count HTTP requests by method, path, and process name
var (
	httpRequestsTotal = /* YOUR CODE HERE */
)

func init() {
	// Register Prometheus metrics
	prometheus.MustRegister(httpRequestsTotal)
}

func main() {
	// Remove resource limits for locked memory
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("failed to remove memlock limit: %v", err)
	}

	// TODO 2: Load eBPF objects
	// Hint: Use loadHttpMonitor() function generated by bpf2go
	// Hint: Don't forget to defer close to cleanup resources
	objs := &httpMonitorObjects{}
	if err := /* YOUR CODE HERE */; err != nil {
		log.Fatalf("failed to load eBPF objects: %v", err)
	}
	defer objs.Close()

	// TODO 3: Attach kprobe to tcp_sendmsg
	// Hint: Use link.Kprobe() with symbol "tcp_sendmsg" and the eBPF program objs.TraceTcpSendmsg
	// Hint: Don't forget to defer close
	kp, err := /* YOUR CODE HERE */
	if err != nil {
		log.Fatalf("failed to attach kprobe: %v", err)
	}
	defer kp.Close()

	log.Println("HTTP monitor started, tracing HTTP requests...")

	// TODO 4: Create ring buffer reader
	// Hint: Use ringbuf.NewReader() with objs.HttpEvents
	rd, err := /* YOUR CODE HERE */
	if err != nil {
		log.Fatalf("failed to create ring buffer reader: %v", err)
	}
	defer rd.Close()

	// Start Prometheus metrics endpoint
	go func() {
		http.Handle("/metrics", promhttp.Handler())
		log.Println("Serving metrics on :9090/metrics")
		if err := http.ListenAndServe(":9090", nil); err != nil {
			log.Fatalf("failed to serve metrics: %v", err)
		}
	}()

	// Handle signals for graceful shutdown
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sig
		log.Println("Received signal, shutting down...")
		os.Exit(0)
	}()

	// Read events from ring buffer
	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				log.Println("Ring buffer closed")
				return
			}
			log.Printf("failed to read from ring buffer: %v", err)
			continue
		}

		// Parse event
		var event httpMonitorHttpEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &event); err != nil {
			log.Printf("failed to parse event: %v", err)
			continue
		}

		// Extract strings (null-terminated)
		comm := nullTerminatedString(event.Comm[:])
		method := nullTerminatedString(event.Method[:])
		path := nullTerminatedString(event.Path[:])

		// Skip if method or path is empty
		if method == "" || path == "" {
			continue
		}

		// Log event
		log.Printf("HTTP request: pid=%d comm=%s method=%s path=%s", event.Pid, comm, method, path)

		// Increment Prometheus counter
		httpRequestsTotal.With(prometheus.Labels{
			"method": method,
			"path":   path,
			"comm":   comm,
		}).Inc()
	}
}

// nullTerminatedString extracts a null-terminated string from a byte slice
func nullTerminatedString(b []byte) string {
	n := bytes.IndexByte(b, 0)
	if n == -1 {
		n = len(b)
	}
	return string(b[:n])
}
