---
apiVersion: v1
kind: Service
metadata:
  name: http-monitor
  namespace: default
  labels:
    app: http-monitor
spec:
  selector:
    app: http-monitor
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
